
name: Build macOS
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ccache
        run: brew install ccache
      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOSRelease
          path: build/bin
